/**
 * @kb/shared
 *
 * Zod schemas + inferred types shared between apps/web and apps/api, plus the
 * generated Supabase `Database` type and the SSE `ChatEvent` union. This
 * package must stay browser-safe: no secrets, no server-only imports.
 *
 * Phase 0 only wires up the package (build, typecheck, workspace linking).
 * The real contents land in later phases:
 *   - Phase 1: `database.types.ts` (generated by `pnpm db:types`)
 *   - Phase 3: `documents.ts` (DocumentCreate/Update/List schemas)
 *   - Phase 5: `chat-events.ts` (the ChatEvent discriminated union)
 */

export const KB_SHARED_VERSION = "0.0.0-phase0";
