/**
 * @kb/shared
 *
 * Zod schemas + inferred types shared between apps/web and apps/api, plus the
 * generated Supabase `Database` type and the SSE `ChatEvent` union. This
 * package must stay browser-safe: no secrets, no server-only imports.
 *
 * Phase 0 only wires up the package (build, typecheck, workspace linking).
 * The real contents landed in later phases:
 *   - Phase 1: `database.types.ts` (generated by `pnpm db:types`)
 *   - Phase 3: `documents.ts` (DocumentCreate/Update/List schemas)
 *   - Phase 5: `chat-events.ts` (the ChatEvent discriminated union) and
 *     `conversations.ts` (chat request + conversation/message DTOs)
 *   - Phase 6: `meta.ts` (the /meta/ai provider-badge response shape) and
 *     `usage.ts` (the /usage page's response shape)
 */

export const KB_SHARED_VERSION = "0.5.0-phase6";

export type { Database, Json, Tables, TablesInsert, TablesUpdate, Enums, CompositeTypes } from "./database.types.js";
export { Constants } from "./database.types.js";

export {
  DocumentCreateSchema,
  DocumentUpdateSchema,
  DocumentListQuerySchema,
  DocumentSummarySchema,
  DocumentDetailSchema,
  DocumentListResponseSchema,
  IndexStatusSchema,
} from "./documents.js";
export type {
  DocumentCreate,
  DocumentUpdate,
  DocumentListQuery,
  DocumentSummary,
  DocumentDetail,
  DocumentListResponse,
  IndexStatus,
} from "./documents.js";

export { ApiErrorResponseSchema } from "./errors.js";
export type { ApiErrorResponse, ApiFieldError } from "./errors.js";

export { ChatEventSchema, ChatFinishReasonSchema, SourceSummarySchema, TokenUsageSchema } from "./chat-events.js";
export type { ChatEvent, ChatFinishReason, SourceSummary, TokenUsage } from "./chat-events.js";

export {
  ChatRequestSchema,
  ChatResponseSchema,
  CitationSnapshotSchema,
  ConversationDetailSchema,
  ConversationListQuerySchema,
  ConversationListResponseSchema,
  ConversationRenameSchema,
  ConversationSummarySchema,
  MessageRoleSchema,
  MessageSchema,
  MessageStatusSchema,
  RetrievalDebugSchema,
} from "./conversations.js";
export type {
  ChatRequest,
  ChatResponse,
  CitationSnapshot,
  ConversationDetail,
  ConversationListQuery,
  ConversationListResponse,
  ConversationRename,
  ConversationSummary,
  Message,
  MessageRole,
  MessageStatus,
  RetrievalDebug,
} from "./conversations.js";

export { AiDescriptorSchema, AiInfoResponseSchema } from "./meta.js";
export type { AiInfoResponse } from "./meta.js";

export { UsageQuerySchema, UsageOperationSchema, UsageDayRowSchema, UsageTotalsSchema, UsageSummaryResponseSchema } from "./usage.js";
export type { UsageQuery, UsageOperation, UsageDayRow, UsageTotals, UsageSummaryResponse } from "./usage.js";
